FROM openjdk:8-jdk-alpine

RUN apk add --no-cache maven
RUN mkdir -p /app/source
COPY . /app/source
WORKDIR /app/source

RUN ./mvnw clean package -DskipTests

EXPOSE 8080

ENTRYPOINT ["java", "-Djava.security.egd=file:/dev/./urandom", "-jar", "target/*.jar"]
